export const aboutPageTemplate = {
  id: "about",
  name: "About Page Template",
  description:
    "Complete About page template with Hero, Content, Statistics, Vision/Mission, and Team sections",
  thumbnail:
    "https://api.builder.io/api/v1/image/assets/TEMP/95eb0e2f9524f8af6f23bb1c251d150d9a1e9b8c?width=200&h=150&fit=crop",
  parents: [
    // Hero Section
    {
      id: 1,
      size: { height: 300, background: "#000000" },
      rnds: [
        {
          id: 1,
          width: 800,
          height: 200,
          x: 150,
          y: 50,
          elements: [
            {
              id: 1,
              type: "text",
              x: 0,
              y: 80,
              width: 800,
              height: 60,
              content: "About Azure Innovations",
              fontSize: 48,
              fontFamily: "Arial, sans-serif",
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "center",
              fontWeight: "400",
              lineHeight: "60px",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
      ],
    },
    // Main Content Section
    {
      id: 2,
      size: { height: 700, background: "#ffffff" },
      rnds: [
        // Text Content
        {
          id: 2,
          width: 664,
          height: 600,
          x: 100,
          y: 50,
          elements: [
            {
              id: 2,
              type: "paragraph",
              x: 0,
              y: 0,
              width: 664,
              height: 600,
              content: `Service Provider for products as well as Apple Corporate partners, having <strong>head office at Naraina (Delhi)</strong> and branch office at Noida, Gurgaon.<br/><br/>We are also <strong>MS Surface Partner</strong>. As an organisation we believe in teamwork, diversity, innovation and integrity. We're driven by professional eminence and always place our customers at the centre of anything and everything we do. Azure Innovations Corporate Background: Azure Innovations, commencing its operations since long. A passionate management team with well experienced Engineers and Professional Business Development team makes Azure Innovations as a best choice for Apple Solutions.<br/><br/>To service, service and service was the commitment we gave to our clients. While this continues to be the bedrock, today we are well established as a Apple Reseller, Service Provider.<br/><br/>This has happened only by virtue of a clear understanding of the future we were seeking and what it takes to achieve that future. So with time and evolving goals came more people, more growth and more importantly an insightful understanding of Apple technology. Our Customer Support services focus on customer satisfaction. The service offerings range from fundamental hardware and software Support to out-tasking services. Based on the combination of flexible support portfolio, pro-active way of working and our focus on the every purchase.`,
              fontSize: 15,
              fontFamily: "Poppins, sans-serif",
              color: "#000000",
              backgroundColor: "transparent",
              textAlign: "justify",
              fontWeight: "300",
              lineHeight: "28px",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
        // Image
        {
          id: 3,
          width: 531,
          height: 640,
          x: 800,
          y: 50,
          elements: [
            {
              id: 3,
              type: "image",
              x: 0,
              y: 0,
              width: 531,
              height: 640,
              content: "",
              imageUrl:
                "https://api.builder.io/api/v1/image/assets/TEMP/95eb0e2f9524f8af6f23bb1c251d150d9a1e9b8c?width=1062",
              borderRadius: 8,
              border: "none",
              objectFit: "cover",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
            },
          ],
        },
      ],
    },
    // Divider
    {
      id: 3,
      size: { height: 50, background: "#ffffff" },
      rnds: [
        {
          id: 4,
          width: 1200,
          height: 1,
          x: 100,
          y: 25,
          elements: [
            {
              id: 4,
              type: "div",
              x: 0,
              y: 0,
              width: 1200,
              height: 1,
              content: "",
              backgroundColor: "#e5e7eb",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
      ],
    },
    // Statistics Section
    {
      id: 4,
      size: { height: 200, background: "#ffffff" },
      rnds: [
        // 20k Happy Customers
        {
          id: 5,
          width: 300,
          height: 120,
          x: 200,
          y: 40,
          elements: [
            {
              id: 5,
              type: "text",
              x: 0,
              y: 0,
              width: 300,
              height: 56,
              content: "20k",
              fontSize: 48,
              fontFamily: "Arial, sans-serif",
              color: "#000000",
              backgroundColor: "transparent",
              textAlign: "center",
              fontWeight: "500",
              lineHeight: "56px",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
            {
              id: 6,
              type: "text",
              x: 0,
              y: 72,
              width: 300,
              height: 28,
              content: "Happy Customers",
              fontSize: 18,
              fontFamily: "Arial, sans-serif",
              color: "#18181b",
              backgroundColor: "transparent",
              textAlign: "center",
              fontWeight: "300",
              lineHeight: "28px",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
        // Divider
        {
          id: 6,
          width: 100,
          height: 1,
          x: 550,
          y: 80,
          elements: [
            {
              id: 7,
              type: "div",
              x: 0,
              y: 0,
              width: 100,
              height: 1,
              content: "",
              background:
                "linear-gradient(to right, #ffffff, #d1d5db, #ffffff)",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
        // 20+ Years Experience
        {
          id: 7,
          width: 300,
          height: 120,
          x: 700,
          y: 40,
          elements: [
            {
              id: 8,
              type: "text",
              x: 0,
              y: 0,
              width: 300,
              height: 56,
              content: "20+",
              fontSize: 48,
              fontFamily: "Arial, sans-serif",
              color: "#000000",
              backgroundColor: "transparent",
              textAlign: "center",
              fontWeight: "500",
              lineHeight: "56px",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
            {
              id: 9,
              type: "text",
              x: 0,
              y: 72,
              width: 300,
              height: 28,
              content: "Year of Experience",
              fontSize: 18,
              fontFamily: "Arial, sans-serif",
              color: "#18181b",
              backgroundColor: "transparent",
              textAlign: "center",
              fontWeight: "300",
              lineHeight: "28px",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
        // Divider
        {
          id: 8,
          width: 100,
          height: 1,
          x: 1050,
          y: 80,
          elements: [
            {
              id: 10,
              type: "div",
              x: 0,
              y: 0,
              width: 100,
              height: 1,
              content: "",
              background:
                "linear-gradient(to right, #ffffff, #d1d5db, #ffffff)",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
        // 100+ Clients Served
        {
          id: 9,
          width: 300,
          height: 120,
          x: 1200,
          y: 40,
          elements: [
            {
              id: 11,
              type: "text",
              x: 0,
              y: 0,
              width: 300,
              height: 56,
              content: "100+",
              fontSize: 48,
              fontFamily: "Arial, sans-serif",
              color: "#000000",
              backgroundColor: "transparent",
              textAlign: "center",
              fontWeight: "500",
              lineHeight: "56px",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
            {
              id: 12,
              type: "text",
              x: 0,
              y: 72,
              width: 300,
              height: 28,
              content: "Clients Served",
              fontSize: 18,
              fontFamily: "Arial, sans-serif",
              color: "#18181b",
              backgroundColor: "transparent",
              textAlign: "center",
              fontWeight: "300",
              lineHeight: "28px",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
      ],
    },
    // Another Divider
    {
      id: 5,
      size: { height: 120, background: "#ffffff" }, // matches your format
      rnds: [
        {
          id: 10,
          width: 1200,
          height: 1,
          x: 100,
          y: 25,
          elements: [
            {
              id: 13,
              type: "div",
              x: 0,
              y: 0,
              width: 1200,
              height: 1,
              content: "",
              backgroundColor: "#e5e7eb",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
      ],
    },
    // Vision/Mission Section
    {
      id: 6,
      size: { height: 350, background: "#ffffff" },
      rnds: [
        // Vision Box
        {
          id: 11,
          width: 610,
          height: 282,
          x: 100,
          y: 40,
          elements: [
            {
              id: 14,
              type: "div",
              x: 0,
              y: 0,
              width: 610,
              height: 282,
              content: "",
              backgroundColor: "#e5e7eb",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 48, right: 48, bottom: 48, left: 48 },
              borderRadius: 0,
              border: "none",
            },
            {
              id: 15,
              type: "text",
              x: 48,
              y: 48,
              width: 514,
              height: 50,
              content: "Our Vision",
              fontSize: 36,
              fontFamily: "Arial, sans-serif",
              color: "#18181b",
              backgroundColor: "transparent",
              textAlign: "left",
              fontWeight: "500",
              lineHeight: "50px",
              margin: { top: 0, right: 0, bottom: 20, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
            {
              id: 16,
              type: "paragraph",
              x: 48,
              y: 118,
              width: 500,
              height: 116,
              content:
                "To be a leading technology partner, delivering innovative Apple and IT solutions that empower our clients to grow, adapt, and succeed in a digital-first world.",
              fontSize: 18,
              fontFamily: "Arial, sans-serif",
              color: "#18181b",
              backgroundColor: "transparent",
              textAlign: "justify",
              fontWeight: "300",
              lineHeight: "28px",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
        // Mission Box
        {
          id: 12,
          width: 610,
          height: 282,
          x: 750,
          y: 40,
          elements: [
            {
              id: 17,
              type: "div",
              x: 0,
              y: 0,
              width: 610,
              height: 282,
              content: "",
              backgroundColor: "#18181b",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 48, right: 48, bottom: 48, left: 48 },
              borderRadius: 0,
              border: "none",
            },
            {
              id: 18,
              type: "text",
              x: 48,
              y: 48,
              width: 514,
              height: 50,
              content: "Our Mission",
              fontSize: 36,
              fontFamily: "Arial, sans-serif",
              color: "#f5f5f5",
              backgroundColor: "transparent",
              textAlign: "left",
              fontWeight: "500",
              lineHeight: "50px",
              margin: { top: 0, right: 0, bottom: 20, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
            {
              id: 19,
              type: "paragraph",
              x: 48,
              y: 118,
              width: 500,
              height: 116,
              content:
                "To provide authentic Apple products, reliable IT solutions, and exceptional customer service through innovation, integrity, and a commitment to continuous improvement.",
              fontSize: 18,
              fontFamily: "Arial, sans-serif",
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "justify",
              fontWeight: "300",
              lineHeight: "28px",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
      ],
    },
    // Team Section
    {
      id: 7,
      size: { height: 700, background: "#000000" },
      rnds: [
        // Section Title
        {
          id: 13,
          width: 1200,
          height: 80,
          x: 100,
          y: 48,
          elements: [
            {
              id: 20,
              type: "text",
              x: 0,
              y: 0,
              width: 1200,
              height: 58,
              content: "Managing Director & Co-Founder",
              fontSize: 40,
              fontFamily: "Arial, sans-serif",
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "left",
              fontWeight: "400",
              lineHeight: "58px",
              margin: { top: 0, right: 0, bottom: 48, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
        // Team Member 1 - Sanjeev Sharma
        {
          id: 14,
          width: 360,
          height: 500,
          x: 100,
          y: 150,
          elements: [
            {
              id: 21,
              type: "div",
              x: 0,
              y: 0,
              width: 360,
              height: 500,
              content: "",
              backgroundColor: "#101010",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 16,
              border: "1px solid #2F2F2F",
            },
            {
              id: 22,
              type: "image",
              x: 0,
              y: 0,
              width: 360,
              height: 360,
              content: "",
              imageUrl: "/assets/images/cofounder.png",
              borderRadius: 8,
              border: "none",
              objectFit: "cover",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            {
              id: 23,
              type: "text",
              x: 16,
              y: 368,
              width: 328,
              height: 40,
              content: "Sanjeev Sharma",
              fontSize: 24,
              fontFamily: "Arial, sans-serif",
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "left",
              fontWeight: "400",
              lineHeight: "32px",
              margin: { top: 8, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
            {
              id: 24,
              type: "text",
              x: 16,
              y: 408,
              width: 328,
              height: 24,
              content: "Managing director and cofounder",
              fontSize: 14,
              fontFamily: "Arial, sans-serif",
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "left",
              fontWeight: "300",
              lineHeight: "20px",
              margin: { top: 0, right: 0, bottom: 16, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
        // Team Member 2 - Jaj Padmakaran
        {
          id: 15,
          width: 360,
          height: 500,
          x: 500,
          y: 150,
          elements: [
            {
              id: 25,
              type: "div",
              x: 0,
              y: 0,
              width: 360,
              height: 500,
              content: "",
              backgroundColor: "#101010",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 16,
              border: "1px solid #2F2F2F",
            },
            {
              id: 26,
              type: "image",
              x: 0,
              y: 0,
              width: 360,
              height: 360,
              content: "",
              imageUrl: "/assets/images/cofounder2.png",
              borderRadius: 8,
              border: "none",
              objectFit: "cover",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            {
              id: 27,
              type: "text",
              x: 16,
              y: 368,
              width: 328,
              height: 40,
              content: "Jaj Padmakaran",
              fontSize: 24,
              fontFamily: "Arial, sans-serif",
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "left",
              fontWeight: "400",
              lineHeight: "32px",
              margin: { top: 8, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
            {
              id: 28,
              type: "text",
              x: 16,
              y: 408,
              width: 328,
              height: 24,
              content: "Technical and Support Services Director",
              fontSize: 14,
              fontFamily: "Arial, sans-serif",
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "left",
              fontWeight: "300",
              lineHeight: "20px",
              margin: { top: 0, right: 0, bottom: 16, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
        // Team Member 3 - Parag Kohli
        {
          id: 16,
          width: 360,
          height: 500,
          x: 900,
          y: 150,
          elements: [
            {
              id: 29,
              type: "div",
              x: 0,
              y: 0,
              width: 360,
              height: 500,
              content: "",
              backgroundColor: "#101010",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 16,
              border: "1px solid #2F2F2F",
            },
            {
              id: 30,
              type: "image",
              x: 0,
              y: 0,
              width: 360,
              height: 360,
              content: "",
              imageUrl: "/assets/images/cofounder3.png",
              borderRadius: 8,
              border: "none",
              objectFit: "cover",
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            {
              id: 31,
              type: "text",
              x: 16,
              y: 368,
              width: 328,
              height: 40,
              content: "Parag Kohli",
              fontSize: 24,
              fontFamily: "Arial, sans-serif",
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "left",
              fontWeight: "400",
              lineHeight: "32px",
              margin: { top: 8, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
            {
              id: 32,
              type: "text",
              x: 16,
              y: 408,
              width: 328,
              height: 24,
              content: "Pre Sales Head",
              fontSize: 14,
              fontFamily: "Arial, sans-serif",
              color: "#ffffff",
              backgroundColor: "transparent",
              textAlign: "left",
              fontWeight: "300",
              lineHeight: "20px",
              margin: { top: 0, right: 0, bottom: 16, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: "none",
            },
          ],
        },
      ],
    },
  ],
};
