// templates/services.js
export const servicesPageTemplate = {
  id: 'services',
  name: 'Our Services',
  description:
    'Professional services page showcasing different service offerings',
  thumbnail:
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200&h=150&fit=crop',
  parents: [
    // Hero Section
    {
      size: {
        height: 450,
        background: 'linear-gradient(135deg, #6c5ce7 0%, #a29bfe 100%)',
      },
      rnds: [
        {
          width: 600,
          height: 180,
          x: 100,
          y: 135,
          elements: [
            {
              type: 'text',
              x: 20,
              y: 20,
              width: 560,
              height: 70,
              content: 'Our Services',
              fontSize: 42,
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 10, right: 20, bottom: 10, left: 20 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'text',
              x: 20,
              y: 100,
              width: 560,
              height: 40,
              content:
                'Comprehensive solutions tailored to your business needs',
              fontSize: 20,
              fontFamily: 'Arial, sans-serif',
              color: '#e8e6ff',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 20, bottom: 5, left: 20 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
      ],
    },
    // Services Grid Section
    {
      size: { height: 600, background: '#ffffff' },
      rnds: [
        // Service 1 - Web Development
        {
          width: 250,
          height: 300,
          x: 50,
          y: 50,
          elements: [
            {
              type: 'image',
              x: 10,
              y: 10,
              width: 230,
              height: 120,
              content: 'Web Development',
              imageUrl:
                'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=200&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 8,
              border: 'none',
            },
            {
              type: 'text',
              x: 10,
              y: 140,
              width: 230,
              height: 30,
              content: 'Web Development',
              fontSize: 20,
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: 10,
              y: 180,
              width: 230,
              height: 80,
              content:
                '<p style="line-height: 1.6;">Custom web applications built with modern technologies. Responsive, fast, and user-friendly solutions.</p>',
              fontSize: 14,
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: 10,
              y: 270,
              width: 100,
              height: 25,
              content: 'Learn More',
              fontSize: 12,
              fontFamily: 'Arial, sans-serif',
              color: '#6c5ce7',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 4,
              border: '1px solid #6c5ce7',
            },
          ],
        },
        // Service 2 - Mobile Apps
        {
          width: 250,
          height: 300,
          x: 320,
          y: 50,
          elements: [
            {
              type: 'image',
              x: 10,
              y: 10,
              width: 230,
              height: 120,
              content: 'Mobile App Development',
              imageUrl:
                'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=400&h=200&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 8,
              border: 'none',
            },
            {
              type: 'text',
              x: 10,
              y: 140,
              width: 230,
              height: 30,
              content: 'Mobile App Development',
              fontSize: 20,
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: 10,
              y: 180,
              width: 230,
              height: 80,
              content:
                '<p style="line-height: 1.6;">Native and cross-platform mobile applications for iOS and Android with seamless user experience.</p>',
              fontSize: 14,
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: 10,
              y: 270,
              width: 100,
              height: 25,
              content: 'Learn More',
              fontSize: 12,
              fontFamily: 'Arial, sans-serif',
              color: '#6c5ce7',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 4,
              border: '1px solid #6c5ce7',
            },
          ],
        },
        // Service 3 - UI/UX Design
        {
          width: 250,
          height: 300,
          x: 590,
          y: 50,
          elements: [
            {
              type: 'image',
              x: 10,
              y: 10,
              width: 230,
              height: 120,
              content: 'UI/UX Design',
              imageUrl:
                'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=200&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 8,
              border: 'none',
            },
            {
              type: 'text',
              x: 10,
              y: 140,
              width: 230,
              height: 30,
              content: 'UI/UX Design',
              fontSize: 20,
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: 10,
              y: 180,
              width: 230,
              height: 80,
              content:
                '<p style="line-height: 1.6;">Beautiful, intuitive user interfaces and experiences that delight users and drive engagement.</p>',
              fontSize: 14,
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: 10,
              y: 270,
              width: 100,
              height: 25,
              content: 'Learn More',
              fontSize: 12,
              fontFamily: 'Arial, sans-serif',
              color: '#6c5ce7',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 4,
              border: '1px solid #6c5ce7',
            },
          ],
        },
        // Service 4 - Digital Marketing
        {
          width: 250,
          height: 300,
          x: 185,
          y: 370,
          elements: [
            {
              type: 'image',
              x: 10,
              y: 10,
              width: 230,
              height: 120,
              content: 'Digital Marketing',
              imageUrl:
                'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=200&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 8,
              border: 'none',
            },
            {
              type: 'text',
              x: 10,
              y: 140,
              width: 230,
              height: 30,
              content: 'Digital Marketing',
              fontSize: 20,
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: 10,
              y: 180,
              width: 230,
              height: 80,
              content:
                '<p style="line-height: 1.6;">Strategic digital marketing campaigns to boost your online presence and drive business growth.</p>',
              fontSize: 14,
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: 10,
              y: 270,
              width: 100,
              height: 25,
              content: 'Learn More',
              fontSize: 12,
              fontFamily: 'Arial, sans-serif',
              color: '#6c5ce7',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 4,
              border: '1px solid #6c5ce7',
            },
          ],
        },
        // Service 5 - Consulting
        {
          width: 250,
          height: 300,
          x: 455,
          y: 370,
          elements: [
            {
              type: 'image',
              x: 10,
              y: 10,
              width: 230,
              height: 120,
              content: 'Business Consulting',
              imageUrl:
                'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=200&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 8,
              border: 'none',
            },
            {
              type: 'text',
              x: 10,
              y: 140,
              width: 230,
              height: 30,
              content: 'Business Consulting',
              fontSize: 20,
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: 10,
              y: 180,
              width: 230,
              height: 80,
              content:
                '<p style="line-height: 1.6;">Expert business consulting to help optimize your operations and achieve your strategic goals.</p>',
              fontSize: 14,
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: 10,
              y: 270,
              width: 100,
              height: 25,
              content: 'Learn More',
              fontSize: 12,
              fontFamily: 'Arial, sans-serif',
              color: '#6c5ce7',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 4,
              border: '1px solid #6c5ce7',
            },
          ],
        },
      ],
    },
  ],
};
